name: provider_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider:
  http:
  hive:
  hive_flutter:
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.4.2
  lottie:
  path_provider:
  permission_handler:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
